/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlydiemthidaihoc.view;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author PC
 */
public class AdminView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public AdminView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnQuanLyDiemThi = new javax.swing.JButton();
        btnQuanLyThiSinh = new javax.swing.JButton();
        btnQuanLyKhoiThi = new javax.swing.JButton();
        btnQuanLyMonThi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html>Quản Lý Điểm Thi Đại Học<br> ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(960, 679));

        btnQuanLyDiemThi.setBackground(new java.awt.Color(0, 0, 102));
        btnQuanLyDiemThi.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btnQuanLyDiemThi.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyDiemThi.setText("<html><div style='text-align: center;'>Quản Lý Điểm Thi<br></div>");
        btnQuanLyDiemThi.setToolTipText("");
        btnQuanLyDiemThi.setBorder(null);
        btnQuanLyDiemThi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuanLyDiemThi.setOpaque(true);
        btnQuanLyDiemThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyDiemThiActionPerformed(evt);
            }
        });

        btnQuanLyThiSinh.setBackground(new java.awt.Color(0, 0, 102));
        btnQuanLyThiSinh.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btnQuanLyThiSinh.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyThiSinh.setText("<html><div style='text-align: center;'> Quản Lý Thí Sinh<br></div>");
        btnQuanLyThiSinh.setToolTipText("");
        btnQuanLyThiSinh.setBorder(null);
        btnQuanLyThiSinh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuanLyThiSinh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQuanLyThiSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyThiSinhActionPerformed(evt);
            }
        });

        btnQuanLyKhoiThi.setBackground(new java.awt.Color(0, 0, 102));
        btnQuanLyKhoiThi.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btnQuanLyKhoiThi.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyKhoiThi.setText("<html><div style='text-align: center;'>Quản Lý Khối Thi<br></div>");
        btnQuanLyKhoiThi.setToolTipText("");
        btnQuanLyKhoiThi.setBorder(null);
        btnQuanLyKhoiThi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuanLyKhoiThi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQuanLyKhoiThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyKhoiThiActionPerformed(evt);
            }
        });

        btnQuanLyMonThi.setBackground(new java.awt.Color(0, 0, 102));
        btnQuanLyMonThi.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btnQuanLyMonThi.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyMonThi.setText("<html><div style='text-align: center;'>Quản Lý Môn Thi<br></div>");
        btnQuanLyMonThi.setToolTipText("");
        btnQuanLyMonThi.setBorder(null);
        btnQuanLyMonThi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuanLyMonThi.setOpaque(true);
        btnQuanLyMonThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyMonThiActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Rockwell", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("<html>Hệ Thống Quản Lý Điểm Thi Đại Học<br> ");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("<html>Xin Chào Admin<br> ");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel9.setIcon(new ImageIcon("src/main/java/com/mycompany/quanlydiemthidaihoc/view/trangchu.jpg"));
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnQuanLyKhoiThi, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuanLyThiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuanLyDiemThi, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuanLyMonThi, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(384, 384, 384))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 1056, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuanLyThiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuanLyDiemThi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuanLyKhoiThi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuanLyMonThi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuanLyDiemThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyDiemThiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuanLyDiemThiActionPerformed

    private void btnQuanLyThiSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyThiSinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuanLyThiSinhActionPerformed

    private void btnQuanLyKhoiThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyKhoiThiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuanLyKhoiThiActionPerformed

    private void btnQuanLyMonThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyMonThiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuanLyMonThiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminView().setVisible(true);
            }
        });
    }
    
    public void addManageThiSinhListener(ActionListener listener) {
        btnQuanLyThiSinh.addActionListener(listener);
    }

    public void addManageKhoiThiListener(ActionListener listener) {
        btnQuanLyKhoiThi.addActionListener(listener);
    }

    public void addManageMonThiListener(ActionListener listener) {
        btnQuanLyMonThi.addActionListener(listener);
    }

    public void addManageDiemThiListener(ActionListener listener) { 
        btnQuanLyDiemThi.addActionListener(listener);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuanLyDiemThi;
    private javax.swing.JButton btnQuanLyKhoiThi;
    private javax.swing.JButton btnQuanLyMonThi;
    private javax.swing.JButton btnQuanLyThiSinh;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
